require: rubocop-rails
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

