require: rubocop-rails
Style/Documentation:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Metrics/LineLength:
  Max: 120
  Enabled: true
  Exclude:
    - spec/**/*.rb
    - config/initializers/devise.rb
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/migrate/*
